/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace TheGraph.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class graph : TBase
  {
    private List<vertex> _V;
    private List<edge> _E;

    public List<vertex> V
    {
      get
      {
        return _V;
      }
      set
      {
        __isset.V = true;
        this._V = value;
      }
    }

    public List<edge> E
    {
      get
      {
        return _E;
      }
      set
      {
        __isset.E = true;
        this._E = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool V;
      public bool E;
    }

    public graph() {
        this.V = new List<vertex>();
        this.E = new List<edge>();
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List) {
                {
                  V = new List<vertex>();
                  TList _list0 = iprot.ReadListBegin();
                  for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                  {
                    vertex _elem2;
                    _elem2 = new vertex();
                    _elem2.Read(iprot);
                    V.Add(_elem2);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  E = new List<edge>();
                  TList _list3 = iprot.ReadListBegin();
                  for( int _i4 = 0; _i4 < _list3.Count; ++_i4)
                  {
                    edge _elem5;
                    _elem5 = new edge();
                    _elem5.Read(iprot);
                    E.Add(_elem5);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("graph");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (V != null && __isset.V) {
          field.Name = "V";
          field.Type = TType.List;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, V.Count));
            foreach (vertex _iter6 in V)
            {
              _iter6.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (E != null && __isset.E) {
          field.Name = "E";
          field.Type = TType.List;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, E.Count));
            foreach (edge _iter7 in E)
            {
              _iter7.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("graph(");
      bool __first = true;
      if (V != null && __isset.V) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("V: ");
        __sb.Append(V);
      }
      if (E != null && __isset.E) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("E: ");
        __sb.Append(E);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
